### ISSUE TITLE
Screenshots not showing up   😞       [ISSUE]

### ISSUE THREAD

**Issue by yarub123** [chrisgrieser/shimmering-obsidian#113]
### Feature Requested

They successfully append the image file name into obsidian but they don't show up as screenshots but rather just the file names, like so:

### Relevant Screenshot

<img width="504" alt="image" src="https://user-images.githubusercontent.com/84487964/215361070-2056871f-aa3b-4306-adc9-ec61a8df6185.png">

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [X] Feature Requests regarding daily notes will not be implemented, since there are [other Alfred workflows that do focus on daily notes already](https://github.com/hauselin/obsidian-alfred).
- [X] If it is an entirely new feature: The requested feature makes more sense to be implemented in Alfred than in a plugin. Please also explain why.

**Comment by chrisgrieser** [comment]
fixed in the latest release: https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.6.1

also, please submit bugs as bug reports and not as feature requests. The form may be longer, but the requested information is often necessary.

**Comment by yarub123** [comment]
@chrisgrieser Yeah man I tried a few times to find the bug report section, it just wasn't popping up on my Firefox to be honest. The only thing it allowed was a feature request, hence why I wrote "[ISSUE]" in the title. Apologies for that, I just had no other way of bringing attention to this. Sorry about that. And thank you for your quick response man, much appreciated. Will support this project this week. 

Peace.

**Comment by chrisgrieser** [comment]
Oh that's weird. I'll look into it what is causing that. Thanks for letting me know!

**Comment by chrisgrieser** [comment]
figured it out, now the bug report form should be available again 🙂

**Comment by yarub123** [comment]
@chrisgrieser Yeah that was weird, what was it? From your end maybe? Thanks for fixing the bug that allows us to use bugs hehe.

**Comment by chrisgrieser** [comment]
nah, the bug report issue was because I made a type in the yaml-file configuring the bug report form, which apparently makes GitHub completely ignore it 🙈

Ok, found the issue. Indeed overlooked a case when you have configured the screenshot path (which I didn't think of, cause you could not use a bug report form, where your config would have be apparent 😅 ) Should be fixed in the latest release: https://github.com/chrisgrieser/shimmering-obsidian/releases/tag/3.6.2

**Comment by yarub123** [comment]
@chrisgrieser Awesome, just double checked it and was freaked out when it didn't work at first. But IT WORKS BEAUTIFULLY. You the man Chris. Great job. 

For anyone that may still have some issues after updating, MAKE SURE TO REINITIALIZE THE SETUP PROCESS AGAIN via Alfred!!
